### ISSUE TITLE
Keep getting failed to send ping

### ISSUE THREAD

**Issue by shuat** [Graylog2/graylog-ansible-role#25]
I followed the instructions for the full playbook
I can login to the application, however I keep getting the following error

```
[graylog-server] failed to send ping to [[#zen_unicast_1#][localhost][inet[/172.20.35.169:9300]
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize exception response from stream
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize exception response from stream
        at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:178)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:130)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)

```
I also tried on 127.0.0.1 with the same error

```
and I do have the latest elastic search

root@ip-172-20-35-169:/home/ubuntu# curl -XGET 'localhost:9200'
{
  "name" : "Sharon Friedlander",
  "cluster_name" : "graylog2",
  "version" : {
    "number" : "2.3.3",
    "build_hash" : "218bdf10790eef486ff2c41a3df5cfa32dadcfde",
    "build_timestamp" : "2016-05-17T15:40:04Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

I am at a loss please help

**Comment by shuat** [comment]
also I made all configs match on 

`elasticsearch_cluster_name = graylog2`
```
cluster.name: graylog2
node.name: graylog-server
node.master: false
node.data: false
transport.tcp.port: 9350
http.enabled: false
discovery.zen.ping.multicast.enabled: False
discovery.zen.ping.unicast.hosts: 172.20.35.169:9300
```
```
################################### Cluster ###################################

cluster.name: graylog2

#################################### Node #####################################

node.master: true
node.data: true

#################################### Index ####################################

index.number_of_shards: 4
index.number_of_replicas: 0

#################################### Paths ####################################


#################################### Plugin ###################################


################################### Memory ####################################

bootstrap.mlockall: false

############################## Network And HTTP ###############################

network.host: 0.0.0.0
#network.host: 127.0.0.1

transport.tcp.port: 9300
transport.tcp.compress: True

http.enabled: true
http.port: 9200
http.max_content_length: 100mb


http.cors.enabled: false


################################### Gateway ###################################

gateway.type:
gateway.recover_after_nodes: 1
gateway.recover_after_time: 5m
gateway.expected_nodes: 1

############################# Recovery Throttling #############################


################################## Discovery ##################################

#discovery.zen.ping.unicast.hosts: 127.0.0.1:9300
discovery.zen.ping.unicast.hosts: 172.20.35.169:9300

################################## Slow Log ##################################


################################## GC Logging ################################
```

**Comment by mariussturm** [comment]
Hi,
please use the 2.0 branch of this role to install Graylog 2.x. Graylog 1.x is not compatible with your  Elasticsearch version.
