### ISSUE TITLE
Issues upgrading from 2.0.3 to version 2.1.0

### ISSUE THREAD

**Issue by garrmark** [Graylog2/graylog-ansible-role#44]
I'm trying to upgrade from version 2.0.3 to version 2.1.0:

My 2.0.3 install was done with the Graylog2.graylog-ansible-role and the following config:
```
- name: set up graylog server
  hosts: graylog
  become: true

  vars:
    elasticsearch_timezone: 'America/New_York'
    elasticsearch_version: '2.x'
    elasticsearch_cluster_name: 'graylog'
    elasticsearch_network_host: '0.0.0.0'
    elasticsearch_gateway_type: ''
    elasticsearch_gateway_expected_nodes: 1
    graylog_install_elastocsearch: yes
    graylog_rest_transport_uri: http://0.0.0.0:12900/
    graylog_password_secret: <removed>
    graylog_root_password_sha2: <removed>
    nginx_sites:
      default:
        - listen 80
        - server_name logs
        - location / {
          proxy_pass http://localhost:9000/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_request_headers on;
          proxy_connect_timeout 150;
          proxy_send_timeout 100;
          proxy_read_timeout 100;
          proxy_buffers 4 32k;
          client_max_body_size 8m;
          client_body_buffer_size 128k; }
  roles:
    - Graylog2.graylog-ansible-role
```
I am then upgrading Graylog2.graylog-ansible-role to version 2.1.0 and removing graylog_rest_transport_uri and adding graylog_web_endpoint_uri like so:
```
- name: set up graylog server
  hosts: graylog
  become: true

  vars:
    elasticsearch_timezone: 'America/New_York'
    elasticsearch_version: '2.x'
    elasticsearch_cluster_name: 'graylog'
    elasticsearch_network_host: '0.0.0.0'
    elasticsearch_gateway_type: ''
    elasticsearch_gateway_expected_nodes: 1
    graylog_install_elastocsearch: yes
    graylog_web_endpoint_uri: http://127.0.0.1:9000/api/
    graylog_password_secret: <removed>
    graylog_root_password_sha2: <removed>
    nginx_sites:
      default:
        - listen 80
        - server_name logs
        - location / {
          proxy_pass http://localhost:9000/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_request_headers on;
          proxy_connect_timeout 150;
          proxy_send_timeout 100;
          proxy_read_timeout 100;
          proxy_buffers 4 32k;
          client_max_body_size 8m;
          client_body_buffer_size 128k; }
  roles:
    - Graylog2.graylog-ansible-role
```   
I get the following errors after running the playbook which indicate an issue with starting grizzly and the port already in use:
```
2016-09-15T15:48:07.215Z INFO  [node] [graylog-server] starting ...
2016-09-15T15:48:07.223Z INFO  [Periodicals] Starting [org.graylog2.periodical.AlertScannerThread] periodical in [10s], polling every [60s].
2016-09-15T15:48:07.224Z INFO  [Periodicals] Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
2016-09-15T15:48:07.224Z INFO  [Periodicals] Starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical in [0s], polling every [20s].
2016-09-15T15:48:07.225Z INFO  [Periodicals] Starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical, running forever.
2016-09-15T15:48:07.226Z INFO  [Periodicals] Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
2016-09-15T15:48:07.227Z INFO  [Periodicals] Starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical in [0s], polling every [30s].
2016-09-15T15:48:07.228Z INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRetentionThread] periodical in [0s], polling every [300s].
2016-09-15T15:48:07.229Z INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRotationThread] periodical in [0s], polling every [10s].
2016-09-15T15:48:07.229Z INFO  [Periodicals] Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
2016-09-15T15:48:07.229Z INFO  [Periodicals] Starting [org.graylog2.periodical.VersionCheckThread] periodical in [300s], polling every [1800s].
2016-09-15T15:48:07.230Z INFO  [Periodicals] Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2016-09-15T15:48:07.230Z INFO  [Periodicals] Starting [org.graylog2.events.ClusterEventPeriodical] periodical in [0s], polling every [1s].
2016-09-15T15:48:07.233Z INFO  [Periodicals] Starting [org.graylog2.events.ClusterEventCleanupPeriodical] periodical in [0s], polling every [300s].
2016-09-15T15:48:07.233Z INFO  [Periodicals] Starting [org.graylog2.periodical.ClusterIdGeneratorPeriodical] periodical, running forever.
2016-09-15T15:48:07.234Z INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRangesMigrationPeriodical] periodical, running forever.
2016-09-15T15:48:07.235Z INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRangesCleanupPeriodical] periodical in [15s], polling every [3600s].
2016-09-15T15:48:07.245Z INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2016-09-15T15:48:07.258Z INFO  [connection] Opened connection [connectionId{localValue:7, serverValue:66}] to 127.0.0.1:27017
2016-09-15T15:48:07.261Z INFO  [connection] Opened connection [connectionId{localValue:8, serverValue:67}] to 127.0.0.1:27017
2016-09-15T15:48:07.264Z INFO  [connection] Opened connection [connectionId{localValue:4, serverValue:64}] to 127.0.0.1:27017
2016-09-15T15:48:07.265Z ERROR [ContentPackLoaderPeriodical] Couldn't list content packs
java.nio.file.NoSuchFileException: data/contentpacks
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_101]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_101]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_101]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[?:1.8.0_101]
	at java.nio.file.Files.newDirectoryStream(Files.java:525) ~[?:1.8.0_101]
	at org.graylog2.periodical.ContentPackLoaderPeriodical.getFiles(ContentPackLoaderPeriodical.java:214) [graylog.jar:?]
	at org.graylog2.periodical.ContentPackLoaderPeriodical.doRun(ContentPackLoaderPeriodical.java:121) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-09-15T15:48:07.278Z INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2016-09-15T15:48:07.285Z INFO  [connection] Opened connection [connectionId{localValue:6, serverValue:65}] to 127.0.0.1:27017
2016-09-15T15:48:07.286Z INFO  [connection] Opened connection [connectionId{localValue:5, serverValue:68}] to 127.0.0.1:27017
2016-09-15T15:48:07.351Z INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.UserPermissionMigrationPeriodical] periodical. Not configured to run on this node.
2016-09-15T15:48:07.351Z INFO  [Periodicals] Starting [org.graylog2.periodical.AlarmCallbacksMigrationPeriodical] periodical, running forever.
2016-09-15T15:48:07.356Z INFO  [Periodicals] Starting [org.graylog2.periodical.ConfigurationManagementPeriodical] periodical, running forever.
2016-09-15T15:48:07.365Z INFO  [Periodicals] Starting [org.graylog2.periodical.LdapGroupMappingMigration] periodical, running forever.
2016-09-15T15:48:07.371Z INFO  [Periodicals] Starting [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical] periodical in [300s], polling every [21600s].
2016-09-15T15:48:07.371Z INFO  [Periodicals] Starting [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical] periodical in [300s], polling every [21600s].
2016-09-15T15:48:07.371Z INFO  [Periodicals] Starting [org.graylog.plugins.collector.periodical.PurgeExpiredCollectorsThread] periodical in [0s], polling every [3600s].
2016-09-15T15:48:07.555Z INFO  [transport] [graylog-server] publish_address {127.0.0.1:9350}, bound_addresses {127.0.0.1:9350}
2016-09-15T15:48:07.563Z INFO  [discovery] [graylog-server] graylog/bG2gqKimQu6vQ9eEPa-DKw
2016-09-15T15:48:07.934Z INFO  [AbstractJerseyService] Enabling CORS for HTTP endpoint
2016-09-15T15:48:10.570Z WARN  [discovery] [graylog-server] waited for 3s and no initial state was set by the discovery
2016-09-15T15:48:10.570Z INFO  [node] [graylog-server] started
2016-09-15T15:48:10.696Z INFO  [service] [graylog-server] detected_master {Grenade}{u81OqBeoQJeAHgX77XJl_Q}{10.0.2.15}{10.0.2.15:9300}{master=true}, added {{Grenade}{u81OqBeoQJeAHgX77XJl_Q}{10.0.2.15}{10.0.2.15:9300}{master=true},}, reason: zen-disco-receive(from master [{Grenade}{u81OqBeoQJeAHgX77XJl_Q}{10.0.2.15}{10.0.2.15:9300}{master=true}])
2016-09-15T15:48:12.548Z INFO  [NetworkListener] Started listener bound to [0.0.0.0:9000]
2016-09-15T15:48:12.549Z INFO  [HttpServer] [HttpServer] Started.
2016-09-15T15:48:12.550Z INFO  [WebInterfaceService] Started Web Interface at <http://0.0.0.0:9000/>
2016-09-15T15:48:17.101Z ERROR [ServiceManager] Service RestApiService [FAILED] has failed in the STARTING state.
javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Address already in use
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:299) ~[graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:163) ~[graylog.jar:?]
	at org.graylog2.shared.initializers.AbstractJerseyService.setUp(AbstractJerseyService.java:160) ~[graylog.jar:?]
	at org.graylog2.shared.initializers.RestApiService.startUp(RestApiService.java:65) ~[graylog.jar:?]
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:60) [graylog.jar:?]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_101]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_101]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_101]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_101]
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:131) ~[graylog.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:88) ~[graylog.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:248) ~[graylog.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:228) ~[graylog.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:219) ~[graylog.jar:?]
	at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:714) ~[graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:278) ~[graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:296) ~[graylog.jar:?]
	... 6 more
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.AlertScannerThread].
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.AlertScannerThread] complete, took <0ms>.
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread].
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] complete, took <0ms>.
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.ClusterHealthCheckThread].
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.ClusterHealthCheckThread] complete, took <0ms>.
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexerClusterCheckerThread].
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexerClusterCheckerThread] complete, took <0ms>.
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexRetentionThread].
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexRetentionThread] complete, took <0ms>.
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexRotationThread].
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexRotationThread] complete, took <0ms>.
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.VersionCheckThread].
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.VersionCheckThread] complete, took <0ms>.
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.ThrottleStateUpdaterThread].
2016-09-15T15:48:17.121Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.ThrottleStateUpdaterThread] complete, took <0ms>.
2016-09-15T15:48:17.122Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.events.ClusterEventPeriodical].
2016-09-15T15:48:17.123Z INFO  [LogManager] Shutting down.
2016-09-15T15:48:17.126Z INFO  [JournalReader] Stopping.
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.events.ClusterEventPeriodical] complete, took <0ms>.
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.events.ClusterEventCleanupPeriodical].
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.events.ClusterEventCleanupPeriodical] complete, took <0ms>.
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexRangesCleanupPeriodical].
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexRangesCleanupPeriodical] complete, took <0ms>.
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical].
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical] complete, took <0ms>.
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical].
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical] complete, took <0ms>.
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutting down periodical [org.graylog.plugins.collector.periodical.PurgeExpiredCollectorsThread].
2016-09-15T15:48:17.127Z INFO  [PeriodicalsService] Shutdown of periodical [org.graylog.plugins.collector.periodical.PurgeExpiredCollectorsThread] complete, took <0ms>.
2016-09-15T15:48:17.132Z ERROR [InputSetupService] Not starting any inputs because lifecycle is: Uninitialized?[LB:DEAD]
2016-09-15T15:48:17.133Z INFO  [WebInterfaceService] Shutting down Web Interface at <http://0.0.0.0:9000/>
2016-09-15T15:48:17.137Z INFO  [Buffers] Waiting until all buffers are empty.
2016-09-15T15:48:17.138Z INFO  [Buffers] All buffers are empty. Continuing.
2016-09-15T15:48:17.142Z INFO  [node] [graylog-server] stopping ...
2016-09-15T15:48:17.142Z INFO  [OutputSetupService] Stopping output org.graylog2.outputs.BlockingBatchedESOutput
2016-09-15T15:48:17.176Z INFO  [node] [graylog-server] stopped
2016-09-15T15:48:17.176Z INFO  [node] [graylog-server] closing ...
2016-09-15T15:48:17.179Z INFO  [node] [graylog-server] closed
2016-09-15T15:48:17.203Z INFO  [LogManager] Shutdown complete.
2016-09-15T15:48:17.223Z INFO  [NetworkListener] Stopped listener bound to [0.0.0.0:9000]
2016-09-15T15:48:17.224Z ERROR [ServerBootstrap] Graylog startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[RestApiService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:713) ~[graylog.jar:?]
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:542) ~[graylog.jar:?]
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:299) ~[graylog.jar:?]
	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:129) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:209) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]
2016-09-15T15:48:17.224Z INFO  [ServiceManagerListener] Services are now stopped.
2016-09-15T15:48:17.242Z INFO  [Server] SIGNAL received. Shutting down.
2016-09-15T15:48:17.250Z INFO  [GracefulShutdown] Graceful shutdown initiated.
2016-09-15T15:48:17.251Z WARN  [DeadEventLoggingListener] Received unhandled event of type <org.graylog2.plugin.lifecycles.Lifecycle> from event bus <AsyncEventBus{graylog-eventbus}>
2016-09-15T15:48:17.251Z INFO  [GracefulShutdown] Node status: [Halting?[LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
2016-09-15T15:48:23.829Z INFO  [CmdLineTool] Loaded plugin: Collector 1.0.3 [org.graylog.plugins.collector.CollectorPlugin]
2016-09-15T15:48:23.829Z INFO  [CmdLineTool] Loaded plugin: Enterprise Integration Plugin 1.0.3 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
2016-09-15T15:48:23.830Z INFO  [CmdLineTool] Loaded plugin: MapWidgetPlugin 1.0.3 [org.graylog.plugins.map.MapWidgetPlugin]
2016-09-15T15:48:23.830Z INFO  [CmdLineTool] Loaded plugin: Pipeline Processor Plugin 1.0.0-beta.5 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
2016-09-15T15:48:23.830Z INFO  [CmdLineTool] Loaded plugin: Anonymous Usage Statistics 2.0.3 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
2016-09-15T15:48:23.975Z INFO  [CmdLineTool] Running with JVM arguments: -Djava.net.preferIPv4Stack=true -Xms1500m -Xmx1500m -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dgraylog2.installation_source=deb
2016-09-15T15:48:26.920Z INFO  [InputBufferImpl] Message journal is enabled.
2016-09-15T15:48:27.184Z INFO  [LogManager] Loading logs.
2016-09-15T15:48:27.315Z INFO  [LogManager] Logs loading complete.
2016-09-15T15:48:27.316Z INFO  [KafkaJournal] Initialized Kafka based journal at /var/lib/graylog-server/journal
```

**Comment by danvaida** [comment]
@garrmark this ansible role is not written to support the upgrade of graylog. should you want to do that, I recommend that you follow the instructions from the graylog docs.

**Comment by garrmark** [comment]
More information.  If I start with a clean OS, and use the same playbook, 2.1 installs and runs fine.  I'm using ubuntu/trusty64.  So it appears to me something that is set up by the 2.0 install and not removed in the 2.1 upgrade.

**Comment by garrmark** [comment]
@danvaida in order for the ansible role to be useful, I think it should support an upgrade.  I suppose we could do a clean install and restore the index from a backup, but that would require a bit more work.  Thoughts?

**Comment by danvaida** [comment]
Have you seen what's the upgrade path from 1.x to 2.x? A role that would do this, even for minor versions upgrade, on RH & Debian platform would turn into a monster. Imagine the tests coverage for the upgrade part... I'm not the role maintainer but I'm definitely advising against that.

**Comment by danvaida** [comment]
Oh, and I'm sorry to hear that you don't find the role useful. Feel free to submit a PR that covers what you want and I'm sure the maintainer will consider it.
Cheers,
Dan.

**Comment by joschi** [comment]
@garrmark 
> ```
javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Address already in use
```

There's simply another instance of Graylog running (probably the old one). Kill the old instance and start the newly installed version of Graylog.

Other than that, @danvaida basically already said the important parts.

**Comment by garrmark** [comment]
How do you guys do upgrades?  I don't need new functionality if there's already a good way to do it.
